var menu = [
  {
    "name": "葱烧排骨",
    "type": "荤菜",
    "taste": "红烧",
    "recipe": "",
  },
  {
    "name": "炒青苗",
    "type": "素菜",
    "taste": "清炒",
    "recipe": "",
   },
  {
    "name": "油麦菜",
    "type": "素菜",
    "taste": "清炒",
    "recipe": "",
   },
  {
    "name": "小炒肉",
    "type": "荤菜",
    "taste": "辣炒",
    "recipe": "",
   },
  {
    "name": "土豆丝",
    "type": "素菜",
    "taste": "炝炒",
    "recipe": "",
   },
  {
    "name": "清蒸尼罗红",
    "type": "荤菜",
    "taste": "清蒸",
    "recipe": "",
   },
  {
    "name": "干锅牛蛙",
    "type": "荤菜",
    "taste": "麻辣",
    "recipe": "",
     },
  {
    "name": "香辣蟹",
    "type": "荤菜",
    "taste": "鲜辣",
    "recipe": "",
       },
  {
    "name": "滑藕片",
    "type": "素菜",
    "taste": "清炒",
    "recipe": "",
  },
  {
    "name": "粉蒸肉",
    "type": "荤菜",
    "taste": "",
    "recipe": "",
  },
  {
        "name": "羊角豆炒肉",
        "type": "荤菜",
        "taste": "咸鲜",
        "recipe": "",
  },
  {
        "name": "芹菜炒香干",
        "type": "素菜",
        "taste": "咸鲜",
        "recipe": "",
  },
  {
        "name": "清炒四季豆",
        "type": "素菜",
        "taste": "清淡",
        "recipe": "",
  },
  {
        "name": "香菇烧鸡翅",
        "type": "荤菜",
        "taste": "咸鲜",
        "recipe": "",
  },
  {
        "name": "辣椒茄子",
        "type": "素菜",
        "taste": "咸辣",
        "recipe": "",
  },
  {
      "name":"蚝油生菜",
      "type":"素菜",
      "taste":"",
      "recipe":"",
  },
  {
      "name": "回锅肉",
      "type": "荤菜",
      "taste": "",
      "recipe": "",    
  },{
          "name": "番茄炒蛋",
          "type": "素菜",
          "taste": "",
          "recipe": "",
  },{
          "name": "节瓜炒肉",
          "type": "荤菜",
          "taste": "",
          "recipe": "",
  },{
          "name": "",
          "type": "",
          "taste": "",
          "recipe": "",
  },{
          "name": "",
          "type": "",
          "taste": "",
          "recipe": "",
  },{
          "name": "",
          "type": "",
          "taste": "",
          "recipe": "",
  },{
          "name": "",
          "type": "",
          "taste": "",
          "recipe": "",
  },
  
]