var menu = [
  {
    "id": "001",
    "name": "红烧排骨",
    "type": "荤菜",
    "taste": "红烧",
    "recipe": "",
  },
  {
    "id": "002",
    "name": "炒青苗",
    "type": "素菜",
    "taste": "清炒",
    "recipe": "",
   },
  {
    "id": "003",
    "name": "油麦菜",
    "type": "素菜",
    "taste": "清炒",
    "recipe": "",
   },
  {
    "id": "004",
    "name": "小炒肉",
    "type": "荤菜",
    "taste": "辣炒",
    "recipe": "",
   },
  {
    "id": "005",
    "name": "土豆丝",
    "type": "素菜",
    "taste": "炝炒",
    "recipe": "",
   },
  {
    "id": "006",
    "name": "清蒸尼罗红",
    "type": "荤菜",
    "taste": "清蒸",
    "recipe": "",
   },
  {
    "id": "007",
    "name": "干锅牛蛙",
    "type": "荤菜",
    "taste": "麻辣",
    "recipe": "",
     },
  {
    "id": "008",
    "name": "香辣蟹",
    "type": "荤菜",
    "taste": "鲜辣",
    "recipe": "",
       },
  {
    "id": "009",
    "name": "滑藕片",
    "type": "素菜",
    "taste": "清炒",
    "recipe": "",
         },
]